### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by karanrajpal14** [aprowe/term-chat#1]
Hey,

I'm unable to start the server on my Ubuntu machine. I get a vague error saying `ReferrenceError: asdop is not defined`

Here's the full stacktrace:
```
➜  ~ termchat --server
/home/karan/.nvm/versions/node/v8.9.4/lib/node_modules/term-chat/src/client.js:8
asdop
^

ReferenceError: asdop is not defined
    at Object.<anonymous> (/home/karan/.nvm/versions/node/v8.9.4/lib/node_modules/term-chat/src/client.js:8:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/karan/.nvm/versions/node/v8.9.4/lib/node_modules/term-chat/index.js:4:14)
    at Module._compile (module.js:643:30)
```

And here are my machine's details:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

Any idea what's going wrong?

**Comment by aprowe** [comment]
Yup, was a typo, just fixed it. 
Version 0.2.5  has it fixed

Thanks!

**Comment by karanrajpal14** [comment]
Works great! Thank you!
